# LOGGING
log_level: "DEBUG" # "INFO"
log_to_file: true
log_file: "agent_rag.log"

debugger: false

# use internet connection
online: True


# Directory containing PDFs
md_dir: "./Markdown_IT"

# Dizionario path
dizionario_path: "./dizionario.xlsx"

# FAISS index persistence
index_dir: "./faiss_index"

# Reindex PDFs or not
reindex: false
workers: 8

# Move index to GPU if available
use_gpu_index: false

# Model quantization
quantization: false

# Embeddings, LLM, reranker
embed_model: "BAAI/bge-m3"   #  8192 tokens.
llm_model: "mistralai/Mistral-Small-24B-Instruct-2501" # "unsloth/Mistral-Small-24B-Instruct-2501-bnb-4bit"
rerank_model: "BAAI/bge-reranker-v2-m3"


# Retrieval
rerank: true
k: 32
k_reranked: 6
search_type: "similarity"  # "similarity" | "mmr"
fetch_k: 120  # only used for MMR
lambda_mult: 0.3  # 0=more diverse, 1=less diverse

threshold: 0.1  # reranker threshold


clean_answer: false

# Chunking
chunk_size: 1200           # number of characters
chunk_overlap: 300
min_chunk_length: 100


# LLM generation
max_new_tokens: 1024
temperature: 0.1
top_p: 0.95
top_k: 40
repetition_penalty: 1.0          # 1.1–1.3 typically. 1.0 means no penalty
no_repeat_ngram_size: 0          # avoid short repeated phrases

# Huggingface cache directory
hf_home: "/fast_disk/models/huggingface"  # "/home/models/HF-Cache"
# hf_home: "/Users/nicola/.cache/huggingface" # Mac

# hf_token is loaded from the HF_TOKEN environment variable (see .env)
# Do NOT set hf_token here


# Interactive options
chat: true

gradio: false
gradio_host: "0.0.0.0"
gradio_port: 7860
gradio_share: false


max_history_turns: 6  # Number of Q&A pairs to remember
