[project]
name = "agentic_rag"
dynamic = ["version"]
description = "Medical Agentic RAG retrieval and LLM pipeline using LangChain"
authors = [
    { name = "Nicola Cantarutti", email = "nicola.cantarutti@uniud.it" }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate",
    "bitsandbytes; sys_platform != 'darwin'",
    "build",
    "faiss-cpu",
    "fasttext",
    "gradio",
    "langchain==1.2.10",
    "langchain_community==0.4.1",
    "langchain_core==1.2.13",
    "langchain_huggingface==1.2.0",
    "langchain_text_splitters==1.1.0",
    "langdetect",
    "langgraph==1.0.8",
    "numpy>=2.4.0",
    "openpyxl",
    "pyyaml",
    "rich",
    "sacremoses",
    "scipy",
    "sentence_transformers",
    "torch==2.9.0",
    "tqdm",
    "transformers>=4.57.1",
    "mlx; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "mlx-lm; sys_platform == 'darwin' and platform_machine == 'arm64'",
]


[project.optional-dependencies]
dev = [
    "ruff",
    "coverage",
    "pre-commit",
    "pytest",
    "jupyter",
    "debugpy",
    "pynvml",
]

[dependency-groups]
dev = [
  "ruff",
  "coverage",
  "pre-commit",
  "pytest",
  "jupyter",
  "debugpy",
  "pynvml",
]



[build-system]
requires = ["setuptools>=65", "wheel", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/agentic_rag/_version.py"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false  # prevent folders without __init__.py from being scanned


[project.scripts]
agentic_rag = "agentic_rag.cli:main"


[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true } }]
environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
  "sys_platform == 'darwin' and platform_machine == 'arm64'",
]


[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = ["spack-repo/packages/py-agentic-rag/package.py"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["UP015"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
per-file-ignores = { "src/agentic_rag/cli.py" = ["I001"] }


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-v --tb=short"
# addopts = "-q --tb=no"
markers = [
    "cpu: tests that run on CPU only",
    "gpu: tests that require GPU",
]
