[base]
name = rag_pdf
files = {[base]name} *.py README.md CHANGELOG.md

[tox]
envlist = py{312, 313}, lint,

[testenv]
deps =
    pytest
    coverage
commands =
    coverage run -m pytest
    coverage report

[testenv:lint]
skip_install = true
allowlist_externals = bash
deps =
    codespell
    pre-commit
commands =
    codespell --config .codespellrc -i 3 -x .codespellignorelines -w {[base]files}
    pre-commit run --all-files --show-diff-on-failure
